"""added names to workoutDays

Revision ID: 33719762f147
Revises: 
Create Date: 2024-08-15 15:56:02.567036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33719762f147'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False, server_default="Workout Day"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_day', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
